git-debimport libtext-iconv-perl_1.7-5.debian.tar.bz2

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -1,80 +1,25 @@
 #!/usr/bin/make -f
-# Made with the aid of dh_make, by Craig Small
-# Sample debian/rules that uses debhelper. GNU copyright 1997 by Joey Hess.
-# Some lines taken from debmake, by Cristoph Lameter.
-# This debian/rules was maintained by Steve Haslam <araqnid@debian.org>.
-# Copyright (C) 2005 Anibal Monsalve Salazar <anibal@debian.org>.
 
-# taken from liblocale-gettext-perl 1.01 -araqnid
+DEB_BUILD_GNU_TYPE      := $(shell dpkg-architecture -qDEB_BUILD_GNU_TYPE)
+DEB_HOST_GNU_TYPE       := $(shell dpkg-architecture -qDEB_HOST_GNU_TYPE)
 
-# Uncomment this to turn on verbose mode.
-export DH_VERBOSE=1
+ifneq ($(DEB_HOST_GNU_TYPE),$(DEB_BUILD_GNU_TYPE))
+        HOST_PERL = $(shell which perl)
+        PERL_VER = $(shell $(HOST_PERL) -v | $(HOST_PERL) -e 'while(<>) {/v(\d+\.\d+\.\d+)/ and print "$$1\n";}')
 
-ifndef PERL
-PERL = /usr/bin/perl
+        export PERL5LIB=/usr/$(DEB_HOST_GNU_TYPE)/lib/perl/$(PERL_VER)
+clean:
+	@if [ ! -f $(PERL5LIB)/Config.pm ] || [ ! -f $(PERL5LIB)/Config_heavy.pl ]	;\
+	then	\
+		echo "Config.pm & Config_heavy.pl for cross building not found in $(PERL5LIB)"	;\
+	exit 1	;\
+	fi
+	dh $@
 endif
 
-TMP     := $(shell pwd)/debian/libtext-iconv-perl
+%:
+	dh $@
 
-build: build-stamp
-build-stamp:
-	dh_testdir
-
-#	Add here commands to compile the package.
-	$(PERL) Makefile.PL INSTALLDIRS=vendor
-	make OPTIMIZE="-O2 -g -Wall"
-	make test
-
-	touch build-stamp
-
-clean:
-	dh_testdir
-	dh_testroot
-	rm -f build-stamp install-stamp
-
-#	Add here commands to clean up after the build process.
-	[ ! -f Makefile ] || $(MAKE) distclean
-
-	dh_clean Makefile Makefile.old
-
-install: install-stamp
-install-stamp: build-stamp
-	dh_testdir
-	dh_testroot
-	dh_prep
-	dh_installdirs
-
-#	Add here commands to install the package into debian/libtext-iconv-perl.
-	$(MAKE) install PREFIX=$(TMP)/usr
-
-	touch install-stamp
-
-# Build architecture-independent files here.
-binary-indep: build install
-# We have nothing to do by default.
-
-# Build architecture-dependent files here.
-binary-arch: build install
-	dh_testdir
-	dh_testroot
-	dh_installdocs
-	dh_installexamples
-	dh_installmenu
-	dh_installcron
-	dh_installman
-	dh_installchangelogs 
-	dh_strip
-	dh_compress
-	dh_fixperms
-	dh_installdeb
+# this package works with only perl-base, it should not depend on perl
+override_dh_perl:
 	dh_perl -d
-	dh_shlibdeps
-	dh_gencontrol
-	dh_md5sums
-	dh_builddeb
-
-source diff:                                                                  
-	@echo >&2 'source and diff are obsolete - use dpkg-source -b'; false
-
-binary: binary-indep binary-arch
-.PHONY: build clean binary-indep binary-arch binary
